
name: Storybook
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      
    - name: install dependencies
      run: yarn install
      
    - name: build module
      run: yarn build
    
    - name: build storybook
      run: yarn build-storybook
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}


#     - name: Deploy to GitHub pages
#       uses: JamesIves/github-pages-deploy-action@3.5.9
#       with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: storybook-pages
#           FOLDER: storybook-static
